#include "pch.h"
#include "SocketTCP.h"

BEGIN_CGMESSAGE_MAP(CSocketTCP)
	CGMESSAGE_TYPE_SUB(CGMESSAGE::SYSTEM::MESSAGE, ((CGMSG_BUFFER&)_Msg).Buffer.front<uint32_t>(4))
	ON_CGMESSAGE(1, ping, CGNETMSG);
END_SUB_CGMESSAGE_MAP
END_CGMESSAGE_MAP